config/routes.rb
BasecampClone::Application.routes.draw do

  devise_for :users

  resources :users
  resources :lists do
    resources :tasks do
      member do
        put 'complete'
      end
    end
  end

  resources :comments
  resources :projects do
    resources :discussions
    resources :text_documents
    match '/members' => 'projects#members_page', via: :get, as: :members
    match '/members' => 'projects#add_member', via: :post, as: :members
    match '/members/remove/:id' => 'projects#remove_member', as: :remove_member
    match '/status' => 'projects#toggle_status', as: :toggle_status
  end

  root :to => "projects#index"

  get "home/index"

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :title, :project_id
  has_many :tasks, dependent: :destroy

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.where(project_id: params[:project_id])
  end

  def show
    @list             = List.find(params[:id])
    @complete_tasks   = @list.tasks.completed
    @incomplete_tasks = @list.tasks.not_completed
    @project          = Project.find(@list.project_id)
  end

  def new
    @list = List.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def create
    params[:list][:project_id] = session[:project_id]
    @list = List.new(params[:list])
    if @list.save
      redirect_to @list
    else
      render action: 'new'
    end
  end
  
  def update
    @list = List.find(params[:id])
    if @list.update_attributes(params[:list])
      redirect_to @list
    else
      render action: 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.haml
= simple_form_for(@list) do |f|
  .form-inputs
    = f.input :title
  .form-actions
    = f.button :submit

app/views/lists/edit.html.haml
%h1 Edit list
= render 'form'

app/views/lists/new.html.haml
%h1 New List
= render 'form'

app/views/lists/show.html.haml
%h1= @list.title
%p
  Created
  = @list.created_at.to_formatted_s(:long_ordinal)
  |
  = link_to "edit", edit_list_path(@list)
  |
  = link_to "delete", @list, method: :delete, 
          confirm: "Are you sure you want to delete this list?"

%hr
%h2 Incomplete Tasks
= link_to "New Task", new_list_task_path(@list), class: "btn btn-small btn-success"
- if @incomplete_tasks.any?
  = form_tag complete_list_task_path(@list), method: :put do
    - @incomplete_tasks.each do |task|
      %p
        = check_box_tag "task_ids[]", task.id
        = task.body
        |
        = link_to "edit", edit_list_task_path(@list, task)
        |
        = link_to "delete", list_task_path(@list, task), method: :delete,
                confirm: "Are you sure you want to delete this task?"
    = submit_tag "Mark as Complete"
- else
  %p No incomplete tasks

%h2 Complete Tasks
- if @complete_tasks.any?
  - @complete_tasks.each do |task|
    %p
      = task.body + " | Completed " + time_ago_in_words(task.updated_at) + "ago | "
      = link_to "delete", list_task_path(@list, task), method: :delete,
                confirm: "Are you sure you want to delete this task?"
- else
  %p No complete tasks


= link_to "back to project", @project