config/routes.rb
BasecampClone::Application.routes.draw do

  devise_for :users

  resources :users
  resources :lists do
    resources :tasks do
      member do
        put 'complete'
      end
    end
  end

  resources :comments
  resources :projects do
    resources :discussions
    resources :text_documents
    match '/members' => 'projects#members_page', via: :get, as: :members
    match '/members' => 'projects#add_member', via: :post, as: :members
    match '/members/remove/:id' => 'projects#remove_member', as: :remove_member
    match '/status' => 'projects#toggle_status', as: :toggle_status
  end

  root :to => "projects#index"

  get "home/index"

end

app/models/text_document.rb
class TextDocument < ActiveRecord::Base
  attr_accessible :body, :project_id, :user_id, :title, :file
  mount_uploader :file, FileUploader
  belongs_to :user
  belongs_to :project

  validates_presence_of :title
  validates_presence_of :body
  validates_presence_of :project_id
  validates_presence_of :user_id

  default_scope order("created_at DESC")

end

app/controllers/text_documents_controller.rb
class TextDocumentsController < ApplicationController
  before_filter :set_project_id

  def set_project_id
    @project ||= Project.find(params[:project_id])
  end

  def show
    @text_document = TextDocument.find(params[:id])
  end

  def new
    @text_document = TextDocument.new
  end

  def create
    params[:text_document][:project_id] = params[:project_id]
    params[:text_document][:user_id] = current_user.id
    @text_document = TextDocument.new(params[:text_document])


    if @text_document.save!
      flash[:success] = "Document created"
      redirect_to_document
    else
      flash[:error] = "Problem creating document."
      render action: 'new'
    end
  end

  def edit
    @text_document = TextDocument.find(params[:id])
  end

  def update
    @text_document = TextDocument.find(params[:id])

    if @text_document.update_attributes(params[:text_document])
      flash[:success] = "Document updated"
      redirect_to_document
    else
      flash[:error] = "Problem updating document"
      render action: 'edit'
    end
  end

  def destroy
    @text_document = TextDocument.find(params[:id])
    flash[:success] = "Document destroyed"
    @text_document.destroy

    redirect_to_project
  end

  private
    def redirect_to_document
      redirect_to project_text_document_path(@text_document.project,
                                             @text_document)
    end

end

app/helpers/text_documents_helper.rb
module TextDocumentsHelper
end

app/views/text_documents/_form.html.haml
= simple_form_for([@project, @text_document]) do |f|
  = f.input :title
  = f.input :body
  = f.input :file
  = f.button :submit

app/views/text_documents/edit.html.haml
%h1 Edit this text document
= render 'form'
= link_to "Back to project", @project

app/views/text_documents/new.html.haml
%h1 Create new text document
= render 'form'
= link_to "Back to project", @project

app/views/text_documents/show.html.haml
%h1.title= @text_document.title
%p.info
  By 
  = link_name @text_document.user
  on 
  = @text_document.created_at.strftime("%a, %b %l, %Y %l:%M %p")
  - if current_user.owns?(@text_document) || current_user.is_admin?
    | 
    = link_to "Edit", edit_project_text_document_path(@text_document.project, @text_document)
%hr
%p.body= @text_document.body
- if @text_document.file?
  %p.file
    %i File:
    = link_to File.basename(@text_document.file.path), @text_document.file.path

.back
  %p= link_to "Back to project", project_path(params[:project_id])