config/routes.rb
BasecampClone::Application.routes.draw do

  devise_for :users

  resources :users
  resources :lists do
    resources :tasks do
      member do
        put 'complete'
      end
    end
  end

  resources :comments
  resources :projects do
    resources :discussions
    resources :text_documents
    match '/members' => 'projects#members_page', via: :get, as: :members
    match '/members' => 'projects#add_member', via: :post, as: :members
    match '/members/remove/:id' => 'projects#remove_member', as: :remove_member
    match '/status' => 'projects#toggle_status', as: :toggle_status
  end

  root :to => "projects#index"

  get "home/index"

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  attr_accessible :message, :project_id, :title, :user_id, :file
  mount_uploader :file, FileUploader
  belongs_to :project
  belongs_to :user

  has_many :comments

  validates_presence_of :title
  validates_presence_of :message
  validates_presence_of :project_id
  validates_presence_of :user_id

  default_scope order("created_at DESC")

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  def index
    redirect_to project_path(params[:project_id])
  end

  def show
    @discussion = Discussion.find(params[:id])
    @project    = Project.find(params[:project_id])
    @comment    = Comment.new
    @comments   = @discussion.comments
  end

  def new
    @discussion = Discussion.new
  end

  def edit
    @discussion = Discussion.find(params[:id])
  end

  def create
    cur_project         = Project.find(params[:project_id])
    @discussion         = cur_project.discussions.new(params[:discussion])
    @discussion.user    = current_user

      if @discussion.save
        redirect_to project_discussion_path(@discussion.project, @discussion),
          notice: 'Discussion was successfully created.'
      else
        render action: "new"
      end
  end

  def update
    @discussion = Discussion.find(params[:id])

    if @discussion.update_attributes(params[:discussion])
      redirect_to project_discussion_path(@discussion.project, @discussion), notice: 'Discussion was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy

    redirect_to project_path(params[:project_id])
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.haml
= simple_form_for(@discussion, url: project_discussions_path) do |f|

  .form-inputs
    = f.input :title
    = f.input :message
    = f.input :file

  .form-actions
    = f.button :submit

app/views/discussions/edit.html.haml
%h1 Editing discussion

= simple_form_for(@discussion, url: project_discussion_path) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :message

  .form-actions
    = f.button :submit

= link_to 'Show', project_discussions_path(@discussion)
= link_to 'Back', project_discussions_path

app/views/discussions/index.html.haml
%h1 Listing discussions

%table
  %tr
    %th Title
    %th Message
    %th Project
    %th User
    %th
    %th
    %th

- @discussions.each do |discussion|
  %tr
    %td= discussion.title %>
    %td= discussion.message %>
    %td= discussion.project_id %>
    %td= discussion.user_id %>
    %td= link_to 'Show', project_discussions_path %>
    %td= link_to 'Edit', edit_project_discussion_path(discussion.project_id, discussion) %>
    %td= link_to 'Destroy', project_discussions_path, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Discussion', new_project_discussion_path

app/views/discussions/new.html.haml
%h1 New discussion

= render 'form'

= link_to 'Back', project_path(params[:project_id])

app/views/discussions/show.html.haml
%p#notice= notice

%h2= @discussion.title

.well.message
  %p.body= @discussion.message
  - if @discussion.file?
    %p.file
      %i File:
      = link_to File.basename(@discussion.file.path), @discussion.file.url
  %p.created
    = link_name(@discussion.user)
    | Posted #{time_ago_in_words(@discussion.created_at)} ago
    - if current_user.owns?(@discussion) || current_user.is_admin?
      |
      = link_to 'Edit', edit_project_discussion_path(@discussion.project_id, @discussion)

= render 'comments/form'
- @comments.each do |comment|
  .well.message
    %p.body= comment.body
    %p.created
      = link_name(comment.user)
      | Posted #{time_ago_in_words(comment.created_at)} ago
      - if current_user.owns?(comment)
        | #{link_to 'Edit', edit_comment_path(comment)}

= link_to 'Back', project_discussions_path