config/routes.rb
BasecampClone::Application.routes.draw do

  devise_for :users

  resources :users
  resources :lists do
    resources :tasks do
      member do
        put 'complete'
      end
    end
  end

  resources :comments
  resources :projects do
    resources :discussions
    resources :text_documents
    match '/members' => 'projects#members_page', via: :get, as: :members
    match '/members' => 'projects#add_member', via: :post, as: :members
    match '/members/remove/:id' => 'projects#remove_member', as: :remove_member
    match '/status' => 'projects#toggle_status', as: :toggle_status
  end

  root :to => "projects#index"

  get "home/index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :due, :status, :title, :user_id

  belongs_to :user
  has_many :discussions
  has_many :text_documents
  has_many :lists, dependent: :destroy

  has_many :memberships, foreign_key: "project_id"
  has_many :members, through: :memberships, source: :user

  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :user_id

  default_scope order("due ASC")
  scope :active, where(status: true)
  scope :archived, where(status: false)

  def archived?
    !status
  end

  def active?
    status
  end

  def files
    files = []
    self.discussions.each do |discussion|
      if discussion.file?
        files << discussion.file
      end
    end
    self.text_documents.each do |discussion|
      if discussion.file?
        files << discussion.file
      end
    end
    files
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  def index
    user_projects      = current_user.projects
    member_of          = current_user.member_of_project

    @active_projects   = user_projects.active + member_of.active
    @archived_projects = user_projects.archived + member_of.archived

    @title = "My Projects"
  end

  def show
    @project = Project.find(params[:id])
    @title = @project.title
    session[:project_id] = @project.id

    @members        = @project.members
    @discussions    = @project.discussions
    @lists          = @project.lists
    @text_documents = @project.text_documents

    objects_for_feed_display = [@discussions, @text_documents,
                                @lists, @members]
    @feeds = ActivityFeed::feed(objects_for_feed_display)
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = current_user.projects.create(params[:project])
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_url
  end
  
  def toggle_status
    project = Project.find(params[:project_id])
    project.toggle!(:status)
    redirect_to project
  end

  def members_page
    @project = Project.find(params[:project_id])
  end

  def add_member
    project = Project.find(params[:project_id])
    user    = User.find_by_email(params[:user_email])
    errors  = []

    if user && !user.nil?
      if params[:user_email] != project.user.email 
        if !project.members.include?(user)
          project.members << user
          redirect_to project, flash: { success: "Member Added." }
        else
          errors << ["Entered email is already a member."]
        end
      else
        errors << ["Entered email is owner of project."]
      end
    else
      errors = ["Could not find entered email."]
    end
    if errors.any?
      redirect_to project_members_path(params[:project_id]),
                    flash: { error: errors.join("<br>") }
    end
  end

  def remove_member
    @member = Membership.where(project_id: params[:project_id],
                              user_id: params[:id]).first
    if @member
      flash[:success] = "Member removed."
      @member.destroy
    else
      flash[:error] = "Error removing member."
    end
    redirect_to project_path(params[:project_id])
    
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def get_status(status)
    return "Active" if status == true
    "Archived"
  end
end

app/views/projects/_discussions.html.haml
.discussions.block
  %h2 Discussions
  = link_to "New Discussion",
    new_project_discussion_path(@project),
    class: "btn btn-success new-discussion-btn"
  - if @discussions.any?
    %table
      - @discussions.each do |discussion|
        %tr
          %td= link_to discussion.title, project_discussion_path(discussion.project_id, discussion)
          %td 
            Created 
            = time_ago_in_words(discussion.created_at)
            ago by 
            = link_name(discussion.user)
  - else
    %p No discussions yet...

app/views/projects/_files.html.haml
%h2 Files
- @project.files.each do |file|
  %p= link_to File.basename(file.path), file.path

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :due

  .form-actions
    = f.button :submit

app/views/projects/_lists.html.haml
.block.lists
  %h2 Todo Lists
  = link_to "New List", new_list_path, class: "btn btn-success"
  - if @lists.any?
    - @lists.each do |list|
      %p
        =link_to list.title, list
        |
        = pluralize(list.tasks.not_completed.count, 'task')
        incomplete
  - else
    %p No lists created yet...

app/views/projects/_sidebar.html.haml
- if current_user.owns?(@project) || current_user.is_admin?
  = link_to 'Edit', edit_project_path(@project),
        class: "btn btn-info", id: "edit-btn"
  = simple_form_for(@project, url: project_toggle_status_path(@project.id) ) do |f|
    - if @project.active?
      = f.submit "Archive this project", class: "btn btn-primary"
    - else
      = f.submit "Activate this project", class: "btn btn-primary"

%h3 Info
%p
  %b Status:
  = get_status(@project.status)
%p
  %b Due in:
  = distance_of_time_in_words(Time.now, @project.due)
  on
  = @project.due.strftime("%b %d")


%h3 Owner
%p= link_name(@project.user)

.members_heading
  %h3 Members
  - if current_user.owns?(@project) || current_user.is_admin?
    = link_to "Add", project_members_path(@project), class: "btn btn-success"
  - else
    - if @project.members.include?(current_user)
      = link_to "Leave", project_remove_member_path(@project.id, current_user.id),
            class: "btn btn-danger"

.members_list
  - if @project.members.any?
    %table
      - @project.members.each do |member|
        %tr
          %td= link_name(member, class: "member")
          - if current_user.owns?(@project) || current_user.is_admin?
            %td
              = simple_form_for(@project, 
                      url: project_remove_member_path(@project.id, member.id),
                      html: { class: "form-inline" } ) do |f|
                = f.submit "Remove", class: "btn btn-small"
  - else
    %p No members just yet...
- if current_user.owns?(@project) || current_user.is_admin?
  .destroy
    = link_to 'Destroy Project', @project,
      method: :delete, data: { confirm: 'Are you sure?' },
      class: "btn btn-danger"

app/views/projects/_text_documents.html.haml
.block.text_documents
  %h2 Text Documents
  = link_to "New Document",
    new_project_text_document_path(@project),
    class: "btn btn-success new-document-btn"

  - if @text_documents.any?
    %table.text_documents
    - @text_documents.each do |text_document|
      %tr
        %td= link_to text_document.title,
          project_text_document_path(text_document.project, text_document)
        %td
          by
          = link_name text_document.user
  - else
    %p No text documents just yet...

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
.action-index
  %h1 My Projects
  = link_to 'New Project', new_project_path,
    class: "btn btn-primary",
    id: "add-project-btn"

  .active_projects.projects.block
    %h2 Active Projects
    - if @active_projects.any?
      %table
        - @active_projects.each do |project|
          %tr
            %td= link_to project.title, project
            %td 
              Due in 
              = distance_of_time_in_words(Time.now, project.due)
            %td 
              Project manager: 
              = link_name(project.user)
    - else
      %p You do not have any projects at this moment...
  .archived_projects.projects.block
    %h2 Archived Projects
    - if @archived_projects.any?
      %table
        - @archived_projects.each do |project|
          %tr
            %td= link_to project.title, project
            %td 
              Due in 
              = distance_of_time_in_words(Time.now, project.due)
            %td 
              Project manager: 
              = link_name(project.user)
    - else
      %p You do not have any archived projects.

app/views/projects/members_page.html.haml
%h1
  Add new user to 
  = @project.title
%p Enter the email of the person you want to add as a member of this project.
= simple_form_for @project,
                      url: { action: "add_member" },
                      method: :post,
                      html: { class: "form-inline" } do |f|
  = text_field_tag "user_email", nil, placeholder: "Email Address",
        data: {autocomplete_source: User.order(:email).map(&:email)}
  = f.submit "Add", class: "btn btn-success"
= link_to "Back to Project", @project, class: "btn btn-primary"

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
.row
  .span8
    %h1= @project.title
    %p#notice= notice

    %p.description
      = @project.description

    = render 'layouts/feed'
    = render 'discussions'
    = render 'lists'
    = render 'text_documents'
    = render 'files'

  .span3.well.sidebar
    = render 'sidebar'